### ISSUE TITLE
__function is not defined

### ISSUE THREAD

**Issue by christianfriedl** [gavinengel/magic-globals#1]
Hi,

---- **the following code:**

require('magic-globals');

function haha() {
    console.log('__line: ' + __line);
    console.log('__file: ' + __file); 
    console.log('__ext: ' + __ext); 
    console.log('__base: ' + __base);
    console.log('__filename: ' + __filename);
    console.log('__dirname: ' + __dirname);
    console.log('__function: ' + __function);
}
haha();

--- **produced on my machine the following output:**

$ node test.js
__line: 4
__file: ...\test
__ext: js
__base: c:\Users\User\Desktop\GitWd\Coding\Mapitor
__filename: c:\Users\User\Desktop\GitWd\Coding\Mapitor\test.js
__dirname: c:\Users\User\Desktop\GitWd\Coding\Mapitor
c:\Users\User\Desktop\GitWd\Coding\Mapitor\test.js:10
console.log('__function: ' + __function);
                             ^
ReferenceError: __function is not defined
    at haha (...\test.js:10:30)
    at Object.<anonymous> ...\test.js:12:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by gavinengel** [comment]
Try `__func` instead of `__function`.
