### ISSUE TITLE
"core.utility.js" when used with __file will return "core"

### ISSUE THREAD

**Issue by MrDrummer** [gavinengel/magic-globals#4]
Pretty simple bug.

I have a file called **core.utility.js**. I do 

console.log(__file )

and it returns **core**

Obviously, I am expecting **core.utility** instead.

I'm using the latest version.

**Comment by gavinengel** [comment]
Thank you for the head's up.

I made a change just now to fix this bug.  By the way I renamed the main file from index.js to magic-globals.js.  

Let me know if doesn't solve the problem.

**Comment by MrDrummer** [comment]
This has fixed the issue. Thanks :)
